apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: projectx
spec:
  instanceProfile: "KARPENTER-INSTANCE-PROFILE"

  amiFamily: AL2023

  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "CLUSTER_NAME_DEFINED_IN_VPC"


  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "CLUSTER_NAME_DEFINED_IN_VPC"
  tags:
    Name: "CLUSTER-NAME-karpenter-node"
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: projectx
spec:
  template:
    metadata:
      labels:
        nodegroup: projectx
    spec:
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: default
      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["t", "m", "r", "c"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["2", "4", "8"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["us-west-1a", "us-west-1c"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot"]
        - key: karpenter.k8s.aws/instance-size
          operator: NotIn
          values: ["nano", "micro", "small"]
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 90s
  limits:
    cpu: "1000"
    memory: 1000Gi
  weight: 10