apiVersion: v1
kind: ServiceAccount
metadata:
  name: projectx-sa
  namespace: projectx
  annotations:
    eks.amazonaws.com/role-arn: IAM-ROLE-ARN

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: projectx-role
  namespace: projectx
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "configmaps", "ingresses", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: projectx-role-binding
  namespace: projectx
subjects:
- kind: ServiceAccount
  name: projectx
  namespace: projectx
roleRef:
  kind: Role
  name: projectx-role
  apiGroup: rbac.authorization.k8s.io