apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: main-certificate
spec:
  issuerRef:
    name: main-issuer
    kind: ClusterIssuer
  commonName: projectx.com
  dnsNames:
    - projectx.com
    - "*.projectx.com"
  secretName: tls-secret
  duration: 2160h #90d
  renewBefore: 360h #15d