apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  namespace: cert-manager
  name: projectx-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: urits91@gmail.com
    privateKeySecretRef:
      name: letsencrypt-cert-manager
    solvers:
    - dns01:
        route53:
          hostedZoneID: ""
          region: ""
      selector:
        dnsZones:
        - "projectx.com"
        - "*.projectx.com"
    - http01:
        ingress:
          class: nginx