apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-data
spec:
  storageClassName: gp3
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: VOL-ID
    fsType: ext4
