apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-crd
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-status-unknown.teams: ArgoCD
    notifications.argoproj.io/subscribe.on-sync-failed.teams: ArgoCD
    notifications.argoproj.io/subscribe.on-sync-succeeded.teams: ArgoCD
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: karpenter
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: public.ecr.aws/karpenter
    targetRevision: "0.37.0"
    chart: karpenter-crd
    helm:
      values: |-

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true