name: "production workflow"
on:
    push:
        branches:
        - prod
        paths:
        - '0-terragrunt/prod/aws/**'
    pull_request:
        branches:
        - prod
        paths:
        - '0-terragrunt/prod/aws/**'

jobs:
    terragrunt-plan-workflow:
        if: ${{ github.event_name == 'pull_request' }}
        permissions:
            id-token: write
            contents: read
            pull-requests: write
        uses: ./.github/workflows/plan.yaml
        with:
            environment: production
            working_directory:  # Specific the working dir for example : './1-prod/aws/eu-central-1'
            aws-region:  # define the region, example: 'eu-central-1'
        secrets:
            token-github: ${{ secrets.TOKEN_GITHUB }}
            aws-oidc-role: ${{ secrets.AWS_OIDC_ROLE }}

    terragrunt-apply-workflow:
        if: ${{ github.event_name == 'push' }}
        permissions:
            id-token: write
            contents: read
            pull-requests: write
        uses: ./.github/workflows/apply.yaml
        with:
            environment: production
            working_directory:  # Specific the working dir for example : './1-prod/aws/eu-central-1'
            aws-region:  # define the region, example: 'eu-central-1'
        secrets:
            token-github: ${{ secrets.TOKEN_GITHUB }}
            aws-oidc-role: ${{ secrets.AWS_OIDC_ROLE }}