apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  instanceProfile: "KARPENTER-INSTANCE-PROFILE"

  amiFamily: AL2023

  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "CLUSTER_NAME_DEFINED_IN_VPC"


  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "CLUSTER_NAME_DEFINED_IN_VPC"
  tags:
    Name: "CLUSTER-NAME-karpenter-node"
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: projectx
spec:
  instanceProfile: "KARPENTER-INSTANCE-PROFILE"

  amiFamily: AL2023

  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "CLUSTER_NAME_DEFINED_IN_VPC"


  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "CLUSTER_NAME_DEFINED_IN_VPC"
  tags:
    Name: "CLUSTER-NAME-karpenter-node"